# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: Npm@1
    displayName: npm custom
    inputs:
      command: custom
      verbose: false      
      customCommand: install -g newman                

  - task: Npm@1
    displayName: npm custom
    inputs:
      command: "custom"
      customCommand: "install newman-reporter-junitfull -g"        
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: newman run $(Build.SourcesDirectory)\WeatherAPI.postman_collection.json -e WeatherAPI.postman_environment.json --insecure --reporters cli,junit --reporter-junit-export junit-report.xml
  - task: PublishTestResults@2
    displayName: Publish Test Results    
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**\*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: false
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**\*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
      #mergeTestResults: false # Optional
      failTaskOnFailedTests: false
      #testRunTitle: # Optional
      #buildPlatform: # Optional
      #buildConfiguration: # Optional
      #publishRunAttachments: true # Optional
      